set_mark (point)
copy_to_register (49, point, mark)
list_registers ()
other_window (1)
set_mark (point)
forward_line ()
copy_region_as_kill (point, mark)
other_window (-1)
yank ()
save_buffer ()
save_buffers_kill_zi ()
