set_mark (point)
forward_line (2)
kill_region (point, mark)
yank ()
yank ()
open_line (1)
forward_line ()
yank ()
forward_line ()
fill_column = 3
fill_paragraph ()
forward_line (-3)
fill_column = 12
fill_paragraph ()
forward_line (-6)
end_of_line ()
fill_column = 33
fill_paragraph ()
save_buffer ()
save_buffers_kill_zi ()
